// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef MOBILEYE_560_660_MSGS__MSG__LKA_NUM_OF_NEXT_LANE_MARKERS_REPORTED_HPP_
#define MOBILEYE_560_660_MSGS__MSG__LKA_NUM_OF_NEXT_LANE_MARKERS_REPORTED_HPP_

#include "mobileye_560_660_msgs/msg/detail/lka_num_of_next_lane_markers_reported__struct.hpp"
#include "mobileye_560_660_msgs/msg/detail/lka_num_of_next_lane_markers_reported__builder.hpp"
#include "mobileye_560_660_msgs/msg/detail/lka_num_of_next_lane_markers_reported__traits.hpp"

#endif  // MOBILEYE_560_660_MSGS__MSG__LKA_NUM_OF_NEXT_LANE_MARKERS_REPORTED_HPP_
