// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_HPP_
#define KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_HPP_

#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__struct.hpp"
#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__builder.hpp"
#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__traits.hpp"

#endif  // KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_HPP_
