// generated from rosidl_generator_c/resource/idl.h.em
// with input from kartech_linear_actuator_msgs:msg/ConfigureOutputsKdFreqDeadbandCmd.idl
// generated code does not contain a copyright notice

#ifndef KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_H_
#define KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_H_

#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__struct.h"
#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__functions.h"
#include "kartech_linear_actuator_msgs/msg/detail/configure_outputs_kd_freq_deadband_cmd__type_support.h"

#endif  // KARTECH_LINEAR_ACTUATOR_MSGS__MSG__CONFIGURE_OUTPUTS_KD_FREQ_DEADBAND_CMD_H_
