// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_HPP_
#define KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_HPP_

#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__struct.hpp"
#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__builder.hpp"
#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__traits.hpp"

#endif  // KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_HPP_
