// generated from rosidl_generator_c/resource/idl.h.em
// with input from kartech_linear_actuator_msgs:msg/PositionReachErrorTimeConfigCmd.idl
// generated code does not contain a copyright notice

#ifndef KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_H_
#define KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_H_

#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__struct.h"
#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__functions.h"
#include "kartech_linear_actuator_msgs/msg/detail/position_reach_error_time_config_cmd__type_support.h"

#endif  // KARTECH_LINEAR_ACTUATOR_MSGS__MSG__POSITION_REACH_ERROR_TIME_CONFIG_CMD_H_
